# Generated by Django 5.2.7 on 2025-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=1000, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
