# Generated by Django 5.2.7 on 2025-11-15 20:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True)),
                ('course_level', models.CharField(choices=[('FRESHMAN', 'Freshman (100-level)'), ('SOPHOMORE', 'Sophomore (200-level)'), ('JUNIOR', 'Junior (300-level)'), ('SENIOR', 'Senior (400-level)'), ('GRADUATE', 'Graduate (500+ level)')], default='FRESHMAN', max_length=20)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
    ]
