# Generated by Django 5.2.7 on 2025-11-15 20:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('professors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(help_text='Full description of what students should be able to do')),
                ('short_name', models.CharField(help_text="Brief identifier (e.g., 'Mathematics & Engineering Knowledge')", max_length=100)),
                ('category', models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('SKILLS', 'Skills'), ('COMPETENCE', 'Competence')], default='KNOWLEDGE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Program Learning Outcome',
                'verbose_name_plural': 'Program Learning Outcomes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('section', models.CharField(default='01', max_length=10)),
                ('capacity', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.CharField(blank=True, help_text="e.g., 'Mon/Wed 10:00-11:30'", max_length=100)),
                ('classroom', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='professors.professor')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'ordering': ['-year', '-semester', 'course'],
                'unique_together': {('course', 'semester', 'year', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FALL', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('grade', models.CharField(blank=True, choices=[('AA', 'AA (4.0)'), ('BA', 'BA (3.5)'), ('BB', 'BB (3.0)'), ('CB', 'CB (2.5)'), ('CC', 'CC (2.0)'), ('DC', 'DC (1.5)'), ('DD', 'DD (1.0)'), ('FD', 'FD (0.5)'), ('FF', 'FF (0.0)')], max_length=2, null=True)),
                ('midterm_grade', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_grade', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-year', '-semester'],
                'unique_together': {('student', 'course', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., 'CLO-1', 'CLO-2'", max_length=20)),
                ('description', models.TextField(help_text='What students should learn in this course')),
                ('bloom_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], help_text="Bloom's Taxonomy cognitive level", max_length=20)),
                ('weight_percentage', models.IntegerField(default=10, help_text='Weight in course assessment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course')),
                ('plo', models.ForeignKey(blank=True, help_text='Which PLO this learning outcome supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_outcomes', to='outcomes.programlearningoutcome')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'ordering': ['course', 'code'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Midterm Exam', 'Final Project'", max_length=200)),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Exam'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment'), ('PRESENTATION', 'Presentation'), ('LAB', 'Lab Work'), ('HOMEWORK', 'Homework'), ('PARTICIPATION', 'Class Participation'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.FloatField(help_text='Maximum possible score', validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_percentage', models.FloatField(help_text='Weight in final grade', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('rubric', models.TextField(blank=True, help_text='Assessment rubric or grading criteria')),
                ('is_graded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_offering', models.ForeignKey(help_text='Which course offering this assessment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='outcomes.courseoffering')),
                ('learning_outcomes', models.ManyToManyField(blank=True, help_text='Which learning outcomes this assessment measures', related_name='assessments', to='outcomes.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['course_offering', 'due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., 'PO-A', 'PO-B'", max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome_type', models.CharField(choices=[('INSTITUTIONAL', 'Institutional Goal'), ('ACCREDITATION', 'Accreditation Requirement'), ('DEPARTMENTAL', 'Departmental Objective'), ('GRADUATE_ATTRIBUTE', 'Graduate Attribute')], default='INSTITUTIONAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_plos', models.ManyToManyField(blank=True, help_text='Which PLOs support this program outcome', related_name='program_outcomes', to='outcomes.programlearningoutcome')),
            ],
            options={
                'verbose_name': 'Program Outcome',
                'verbose_name_plural': 'Program Outcomes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CoursePLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_level', models.CharField(choices=[('INTRODUCTORY', 'Introductory (1)'), ('REINFORCING', 'Reinforcing (2)'), ('MASTERY', 'Mastery (3)')], default='REINFORCING', help_text='Level at which this course addresses the PLO', max_length=20)),
                ('assessment_method', models.TextField(blank=True, help_text="How this PLO is assessed in the course (e.g., 'Project-based evaluation', 'Written exam')")),
                ('weight_percentage', models.IntegerField(default=10, help_text='Weight of this PLO in overall course assessment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_mappings', to='courses.course')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='outcomes.programlearningoutcome')),
            ],
            options={
                'verbose_name': 'Course-PLO Mapping',
                'verbose_name_plural': 'Course-PLO Mappings',
                'ordering': ['course', 'plo__number'],
                'unique_together': {('course', 'plo')},
            },
        ),
        migrations.CreateModel(
            name='StudentPLOAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_level', models.CharField(choices=[('NOT_ACHIEVED', 'Not Achieved'), ('PARTIALLY', 'Partially Achieved'), ('ACHIEVED', 'Achieved'), ('EXCEEDED', 'Exceeded')], max_length=20)),
                ('score', models.FloatField(help_text='Numerical score for this PLO in this course', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_achievements', to='outcomes.enrollment')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='outcomes.programlearningoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_achievements', to='students.student')),
            ],
            options={
                'verbose_name': 'Student PLO Achievement',
                'verbose_name_plural': 'Student PLO Achievements',
                'ordering': ['-assessed_at'],
                'unique_together': {('student', 'plo', 'enrollment')},
            },
        ),
    ]
