# Generated by Django 5.2.7 on 2025-11-16 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.FloatField(help_text='How much this assessment contributes to the LO (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_mappings', to='outcomes.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='outcomes.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment-LO Mapping',
                'verbose_name_plural': 'Assessment-LO Mappings',
                'unique_together': {('assessment', 'learning_outcome')},
            },
        ),
        migrations.CreateModel(
            name='LOPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Weight of LO contribution to PO (1-5 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mappings', to='outcomes.learningoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_mappings', to='outcomes.programoutcome')),
            ],
            options={
                'verbose_name': 'LO-PO Mapping',
                'verbose_name_plural': 'LO-PO Mappings',
                'unique_together': {('learning_outcome', 'program_outcome')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text="Student's score on this assessment", validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='outcomes.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='outcomes.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Assessment Score',
                'verbose_name_plural': 'Student Assessment Scores',
                'ordering': ['-graded_at'],
                'unique_together': {('student', 'assessment', 'enrollment')},
            },
        ),
    ]
